// Companion sidecar files that live beside a PDF.
//
// Two independent things share this header because they share the "sidecar
// beside the PDF" shape, but they are not the same feature and must not be
// confused:
//
//   <base>.toc / <base>.json     topics -- the middle pane's list, usually
//                                machine-generated by TocGen, hand-editable.
//   <base>.bookmarks.json        the user's own Ctrl+B bookmarks.
//
// The double extension on the bookmarks sidecar is deliberate: it keeps
// manual.bookmarks.json from being picked up as manual.pdf's *topics* file by
// find_metadata_path, which searches for <base>.json.
//
// Ported from app.py's find_metadata_path / _parse_toc_text /
// _parse_json_metadata / load_metadata / bookmarks_path / load_bookmarks /
// save_bookmarks.  Behaviour is deliberately identical, including the error
// text, because both apps read the same files on disk.

#ifndef PDFSHERPA_APP_METADATA_H
#define PDFSHERPA_APP_METADATA_H

#include <filesystem>
#include <optional>
#include <string>
#include <vector>

namespace pdfsherpa {

// Extensions searched for a topics file, in order of preference.  Matches
// app.py's METADATA_EXTENSIONS -- the order is load-bearing, since a PDF may
// legitimately have both and .toc wins.
inline constexpr const char* kMetadataExtensions[] = {".toc", ".json"};

struct TopicEntry {
    std::string topic;  // UTF-8
    int page = 1;       // 1-based, as written in the file
};

struct Bookmark {
    int page = 1;       // 1-based
    std::string title;  // UTF-8, never empty (blank titles are dropped)
};

// Topic loading can fail in ways the user must see (bad syntax in a file they
// hand-edited), so failure carries a message rather than collapsing to an
// empty list.  An empty `entries` with ok == true is the distinct, non-error
// "file parsed but held no topics" case, which the UI reports differently.
struct TopicLoadResult {
    bool ok = false;
    std::vector<TopicEntry> entries;
    std::string error;  // UTF-8, empty when ok
};

// The topics file for a PDF, or nullopt when it has none.
std::optional<std::filesystem::path> find_metadata_path(
    const std::filesystem::path& pdf_path);

// Parse the plain-text .toc format.  Each non-comment, non-blank line ends
// with a page number; the topic is everything before the last ':' (or before
// the last space when the line has no colon), so topics may themselves contain
// colons and dashes -- "Chapter 1 - Setup: 5" is one topic, not two.
TopicLoadResult parse_toc_text(std::string_view text);

// Parse the .json topics format: an array of {"topic": str, "page": int}.
TopicLoadResult parse_json_metadata(std::string_view text);

// Read a topics file, dispatching on its extension.
TopicLoadResult load_metadata(const std::filesystem::path& metadata_path);

// manual.pdf -> manual.bookmarks.json
std::filesystem::path bookmarks_path(const std::filesystem::path& pdf_path);

// A PDF's bookmarks, sorted by page.  A missing sidecar is the normal case and
// yields an empty list, not an error.  `warning` is set only when a sidecar
// exists but could not be read, which the caller surfaces before the next save
// overwrites it.
std::vector<Bookmark> load_bookmarks(const std::filesystem::path& pdf_path,
                                     std::string* warning = nullptr);

// Write a PDF's bookmarks sidecar.  An empty list deletes the file: no file
// means no bookmarks, which is what keeps a cleared PDF from leaving an empty
// sidecar behind.  Returns false if the write (or delete) failed.
bool save_bookmarks(const std::filesystem::path& pdf_path,
                    const std::vector<Bookmark>& bookmarks);

}  // namespace pdfsherpa

#endif  // PDFSHERPA_APP_METADATA_H
